// Code generated by go-bindata.
// sources:
// static/css/index_style.css
// static/css/overview_style.css
// static/export_list.json
// static/index.html
// static/js/d3.min.js
// static/js/d3utils.js
// static/js/jquery-1.8.3.min.js
// static/js/overview.js
// static/js/render_settings.js
// static/js/render_settings_example.js
// static/js/render_utils.js
// static/js/spin.min.js
// static/js/ulogme.js
// static/js/ulogme_common.js
// static/js/underscore.min.js
// static/overview.html
// static/rules.json
// DO NOT EDIT!

package main

import (
	"fmt"
	"io/ioutil"
	"os"
	"path/filepath"
	"strings"
)

// bindataRead reads the given file from disk. It returns an error on failure.
func bindataRead(path, name string) ([]byte, error) {
	buf, err := ioutil.ReadFile(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset %s at %s: %v", name, path, err)
	}
	return buf, err
}

type asset struct {
	bytes []byte
	info  os.FileInfo
}

// staticCssIndex_styleCss reads file data from disk. It returns an error on failure.
func staticCssIndex_styleCss() (*asset, error) {
	path := "/home/hxr/work/go/src/github.com/erasche/gologme/server/static/css/index_style.css"
	name := "static/css/index_style.css"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// staticCssOverview_styleCss reads file data from disk. It returns an error on failure.
func staticCssOverview_styleCss() (*asset, error) {
	path := "/home/hxr/work/go/src/github.com/erasche/gologme/server/static/css/overview_style.css"
	name := "static/css/overview_style.css"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// staticExport_listJson reads file data from disk. It returns an error on failure.
func staticExport_listJson() (*asset, error) {
	path := "/home/hxr/work/go/src/github.com/erasche/gologme/server/static/export_list.json"
	name := "static/export_list.json"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// staticIndexHtml reads file data from disk. It returns an error on failure.
func staticIndexHtml() (*asset, error) {
	path := "/home/hxr/work/go/src/github.com/erasche/gologme/server/static/index.html"
	name := "static/index.html"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// staticJsD3MinJs reads file data from disk. It returns an error on failure.
func staticJsD3MinJs() (*asset, error) {
	path := "/home/hxr/work/go/src/github.com/erasche/gologme/server/static/js/d3.min.js"
	name := "static/js/d3.min.js"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// staticJsD3utilsJs reads file data from disk. It returns an error on failure.
func staticJsD3utilsJs() (*asset, error) {
	path := "/home/hxr/work/go/src/github.com/erasche/gologme/server/static/js/d3utils.js"
	name := "static/js/d3utils.js"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// staticJsJquery183MinJs reads file data from disk. It returns an error on failure.
func staticJsJquery183MinJs() (*asset, error) {
	path := "/home/hxr/work/go/src/github.com/erasche/gologme/server/static/js/jquery-1.8.3.min.js"
	name := "static/js/jquery-1.8.3.min.js"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// staticJsOverviewJs reads file data from disk. It returns an error on failure.
func staticJsOverviewJs() (*asset, error) {
	path := "/home/hxr/work/go/src/github.com/erasche/gologme/server/static/js/overview.js"
	name := "static/js/overview.js"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// staticJsRender_settingsJs reads file data from disk. It returns an error on failure.
func staticJsRender_settingsJs() (*asset, error) {
	path := "/home/hxr/work/go/src/github.com/erasche/gologme/server/static/js/render_settings.js"
	name := "static/js/render_settings.js"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// staticJsRender_settings_exampleJs reads file data from disk. It returns an error on failure.
func staticJsRender_settings_exampleJs() (*asset, error) {
	path := "/home/hxr/work/go/src/github.com/erasche/gologme/server/static/js/render_settings_example.js"
	name := "static/js/render_settings_example.js"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// staticJsRender_utilsJs reads file data from disk. It returns an error on failure.
func staticJsRender_utilsJs() (*asset, error) {
	path := "/home/hxr/work/go/src/github.com/erasche/gologme/server/static/js/render_utils.js"
	name := "static/js/render_utils.js"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// staticJsSpinMinJs reads file data from disk. It returns an error on failure.
func staticJsSpinMinJs() (*asset, error) {
	path := "/home/hxr/work/go/src/github.com/erasche/gologme/server/static/js/spin.min.js"
	name := "static/js/spin.min.js"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// staticJsUlogmeJs reads file data from disk. It returns an error on failure.
func staticJsUlogmeJs() (*asset, error) {
	path := "/home/hxr/work/go/src/github.com/erasche/gologme/server/static/js/ulogme.js"
	name := "static/js/ulogme.js"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// staticJsUlogme_commonJs reads file data from disk. It returns an error on failure.
func staticJsUlogme_commonJs() (*asset, error) {
	path := "/home/hxr/work/go/src/github.com/erasche/gologme/server/static/js/ulogme_common.js"
	name := "static/js/ulogme_common.js"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// staticJsUnderscoreMinJs reads file data from disk. It returns an error on failure.
func staticJsUnderscoreMinJs() (*asset, error) {
	path := "/home/hxr/work/go/src/github.com/erasche/gologme/server/static/js/underscore.min.js"
	name := "static/js/underscore.min.js"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// staticOverviewHtml reads file data from disk. It returns an error on failure.
func staticOverviewHtml() (*asset, error) {
	path := "/home/hxr/work/go/src/github.com/erasche/gologme/server/static/overview.html"
	name := "static/overview.html"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// staticRulesJson reads file data from disk. It returns an error on failure.
func staticRulesJson() (*asset, error) {
	path := "/home/hxr/work/go/src/github.com/erasche/gologme/server/static/rules.json"
	name := "static/rules.json"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}

// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if err != nil {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func AssetInfo(name string) (os.FileInfo, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, fmt.Errorf("AssetInfo %s not found", name)
}

// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string]func() (*asset, error){
	"static/css/index_style.css": staticCssIndex_styleCss,
	"static/css/overview_style.css": staticCssOverview_styleCss,
	"static/export_list.json": staticExport_listJson,
	"static/index.html": staticIndexHtml,
	"static/js/d3.min.js": staticJsD3MinJs,
	"static/js/d3utils.js": staticJsD3utilsJs,
	"static/js/jquery-1.8.3.min.js": staticJsJquery183MinJs,
	"static/js/overview.js": staticJsOverviewJs,
	"static/js/render_settings.js": staticJsRender_settingsJs,
	"static/js/render_settings_example.js": staticJsRender_settings_exampleJs,
	"static/js/render_utils.js": staticJsRender_utilsJs,
	"static/js/spin.min.js": staticJsSpinMinJs,
	"static/js/ulogme.js": staticJsUlogmeJs,
	"static/js/ulogme_common.js": staticJsUlogme_commonJs,
	"static/js/underscore.min.js": staticJsUnderscoreMinJs,
	"static/overview.html": staticOverviewHtml,
	"static/rules.json": staticRulesJson,
}

// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//     data/
//       foo.txt
//       img/
//         a.png
//         b.png
// then AssetDir("data") would return []string{"foo.txt", "img"}
// AssetDir("data/img") would return []string{"a.png", "b.png"}
// AssetDir("foo.txt") and AssetDir("notexist") would return an error
// AssetDir("") will return []string{"data"}.
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		cannonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(cannonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, fmt.Errorf("Asset %s not found", name)
			}
		}
	}
	if node.Func != nil {
		return nil, fmt.Errorf("Asset %s not found", name)
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}

type bintree struct {
	Func     func() (*asset, error)
	Children map[string]*bintree
}
var _bintree = &bintree{nil, map[string]*bintree{
	"static": &bintree{nil, map[string]*bintree{
		"css": &bintree{nil, map[string]*bintree{
			"index_style.css": &bintree{staticCssIndex_styleCss, map[string]*bintree{}},
			"overview_style.css": &bintree{staticCssOverview_styleCss, map[string]*bintree{}},
		}},
		"export_list.json": &bintree{staticExport_listJson, map[string]*bintree{}},
		"index.html": &bintree{staticIndexHtml, map[string]*bintree{}},
		"js": &bintree{nil, map[string]*bintree{
			"d3.min.js": &bintree{staticJsD3MinJs, map[string]*bintree{}},
			"d3utils.js": &bintree{staticJsD3utilsJs, map[string]*bintree{}},
			"jquery-1.8.3.min.js": &bintree{staticJsJquery183MinJs, map[string]*bintree{}},
			"overview.js": &bintree{staticJsOverviewJs, map[string]*bintree{}},
			"render_settings.js": &bintree{staticJsRender_settingsJs, map[string]*bintree{}},
			"render_settings_example.js": &bintree{staticJsRender_settings_exampleJs, map[string]*bintree{}},
			"render_utils.js": &bintree{staticJsRender_utilsJs, map[string]*bintree{}},
			"spin.min.js": &bintree{staticJsSpinMinJs, map[string]*bintree{}},
			"ulogme.js": &bintree{staticJsUlogmeJs, map[string]*bintree{}},
			"ulogme_common.js": &bintree{staticJsUlogme_commonJs, map[string]*bintree{}},
			"underscore.min.js": &bintree{staticJsUnderscoreMinJs, map[string]*bintree{}},
		}},
		"overview.html": &bintree{staticOverviewHtml, map[string]*bintree{}},
		"rules.json": &bintree{staticRulesJson, map[string]*bintree{}},
	}},
}}

// RestoreAsset restores an asset under the given directory
func RestoreAsset(dir, name string) error {
	data, err := Asset(name)
	if err != nil {
		return err
	}
	info, err := AssetInfo(name)
	if err != nil {
		return err
	}
	err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
	if err != nil {
		return err
	}
	err = ioutil.WriteFile(_filePath(dir, name), data, info.Mode())
	if err != nil {
		return err
	}
	err = os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
	if err != nil {
		return err
	}
	return nil
}

// RestoreAssets restores an asset under the given directory recursively
func RestoreAssets(dir, name string) error {
	children, err := AssetDir(name)
	// File
	if err != nil {
		return RestoreAsset(dir, name)
	}
	// Dir
	for _, child := range children {
		err = RestoreAssets(dir, filepath.Join(name, child))
		if err != nil {
			return err
		}
	}
	return nil
}

func _filePath(dir, name string) string {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	return filepath.Join(append([]string{dir}, strings.Split(cannonicalName, "/")...)...)
}

